import gzip
import os
import re

SRC_DIR = "src"

def minify_html(html: str) -> str:
    # Tags where whitespace should be preserved
    preserve_tags = ['pre', 'code', 'textarea', 'script', 'style']
    preserve_regex = '|'.join(preserve_tags)

    # Protect preserve blocks with placeholders
    preserve_blocks = []
    def preserve(match):
        preserve_blocks.append(match.group(0))
        return f"__PRESERVE_BLOCK_{len(preserve_blocks)-1}__"

    html = re.sub(rf'<({preserve_regex})[\s\S]*?</\1>', preserve, html, flags=re.IGNORECASE)

    # Remove HTML comments
    html = re.sub(r'<!--.*?-->', '', html, flags=re.DOTALL)

    # Collapse all whitespace between tags
    html = re.sub(r'>\s+<', '><', html)

    # Collapse multiple spaces inside tags
    html = re.sub(r'\s+', ' ', html)

    # Restore preserved blocks
    for i, block in enumerate(preserve_blocks):
        html = html.replace(f"__PRESERVE_BLOCK_{i}__", block)

    return html.strip()

def minify_js(js: str) -> str:
    # Simple JS minification - remove comments and extra whitespace
    # Remove single-line comments (but preserve URLs like http://)
    js = re.sub(r'(?<!:)//.*?$', '', js, flags=re.MULTILINE)
    # Remove multi-line comments
    js = re.sub(r'/\*.*?\*/', '', js, flags=re.DOTALL)
    # Collapse multiple spaces/newlines to single space
    js = re.sub(r'\s+', ' ', js)
    # Remove spaces around operators and punctuation
    js = re.sub(r'\s*([{}();,:])\s*', r'\1', js)
    return js.strip()

def process_file(file_path: str, file_type: str):
    """Process HTML or JS file and generate compressed header"""
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Minify based on file type
    if file_type == "html":
        minified = minify_html(content)
        base_name = f"{os.path.splitext(os.path.basename(file_path))[0]}Html"
    else:  # js
        minified = minify_js(content)
        # Convert filename to CamelCase for variable name
        filename = os.path.splitext(os.path.basename(file_path))[0]
        # Handle i18n/en.js -> I18nEn, i18n/ru.js -> I18nRu, i18n.js -> I18n
        base_name = ''.join(word.capitalize() for word in filename.replace('_', ' ').replace('-', ' ').split()) + "Js"

    compressed = gzip.compress(minified.encode('utf-8'), compresslevel=9)
    header_path = os.path.join(os.path.dirname(file_path), f"{base_name}.generated.h")

    with open(header_path, "w", encoding="utf-8") as h:
        h.write("// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY\n\n")
        h.write("#pragma once\n\n")
        h.write("#include <cstddef>\n\n")
        h.write(f"constexpr char {base_name}[] PROGMEM = {{\n")
        for i in range(0, len(compressed), 16):
            chunk = compressed[i:i+16]
            hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
            h.write(f"    {hex_vals},\n")
        h.write("};\n")
        h.write(f"constexpr size_t {base_name}CompressedSize = sizeof({base_name});\n")

    original_size = len(content)
    minified_size = len(minified.encode('utf-8'))
    compressed_size = len(compressed)
    print(f"Generated: {header_path} ({original_size} → {minified_size} → {compressed_size} bytes)")

for root, _, files in os.walk(SRC_DIR):
    for file in files:
        file_path = os.path.join(root, file)
        if file.endswith(".html"):
            process_file(file_path, "html")
        elif file.endswith(".js"):
            process_file(file_path, "js")
